# Exportar los registros clínicos en formato CSV
exporter.csv.export = true

# Desactivar FHIR porque este laboratorio sólo necesita CSV
exporter.fhir.export = false
exporter.hospital.fhir.export = false

# Directorio de salida
exporter.baseDirectory = ./lab02/data/pilot

# Conservar diez años de historia clínica
exporter.years_of_history = 10
