FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./

RUN python -m pip install \
    --no-cache-dir \
    uv==0.12.13

RUN uv sync \
    --locked \
    --extra dev \
    --no-install-project \
    --no-cache

COPY src ./src
COPY tests ./tests

RUN uv sync \
    --locked \
    --extra dev \
    --no-cache

ENV PATH="/app/.venv/bin:$PATH"

CMD ["pytest"]
