FROM python:3.12-slim AS builder

WORKDIR /app

RUN python -m pip install \
    --no-cache-dir \
    uv==0.12.13

COPY pyproject.toml uv.lock README.md ./

RUN uv sync \
    --locked \
    --extra dev \
    --no-install-project \
    --no-cache

COPY src ./src

RUN uv sync \
    --locked \
    --extra dev \
    --no-editable \
    --no-cache

FROM python:3.12-slim AS runtime

ENV VIRTUAL_ENV="/app/.venv"
ENV PATH="/app/.venv/bin:$PATH"

WORKDIR /app

COPY --from=builder /app/.venv /app/.venv

COPY pyproject.toml ./pyproject.toml
COPY tests ./tests

CMD ["pytest"]
